feat: add expression rule support
hertz-contrib/casbin pull request #3
Opened 2023-02-06 10:31 UTC by StellarisW

#### What type of PR is this?

feat

#### What this PR does / why we need it (en: English/zh: Chinese):

en: add permission checks mode - "CUSTOM"
zh:  添加 permission 检测模式 - "自定义"，用于解析 "A && B || C", "A && !B"等场景

#### Which issue(s) this PR fixes:

2023-02-06 11:47 UTC, L2ncE commented on option.go
> +		PermissionSeparator: DefaultPermissionSeparator,
Using `OptionsDefault.PermissionSeparator`

2023-02-06 11:47 UTC, L2ncE commented on option.go
> +	PermissionSeparator string
Add comment

2023-02-06 11:47 UTC, L2ncE commented on casbin.go
> +	"github.com/Knetic/govaluate"
Use two-stage & Can we not import third-party libraries

2023-02-06 11:47 UTC, L2ncE commented on casbin.go
> +
Delete useless blank

2023-02-06 11:47 UTC, L2ncE commented on casbin.go
> +
ditto

2023-02-06 11:49 UTC, L2ncE commented
Can you restore the code in the original example and create a new folder in the example to put the `CUSTOM` sample?REAMDE is the same.

2023-02-07 01:56 UTC, L2ncE requested changes

2023-02-07 01:56 UTC, L2ncE commented on README.md
> +- `WithLogic(logic Logic)`
You can put these in the documentation and leave only the critical parts here

2023-02-07 01:56 UTC, L2ncE commented on casbin.go
> +
Use `utils.H` instead of `map[string]interface{}`

2023-02-07 02:17 UTC, L2ncE commented on casbin.go
> +	"github.com/cloudwego/hertz/pkg/common/utils"
two-stage

2023-02-07 02:27 UTC, L2ncE approved these changes

2023-02-07 03:27 UTC, merged

2023-02-07 03:27 UTC, li-jin-gou commented
LGTM